$ROOT_PATH = pwd
$INDEX_PATH = "$($ROOT_PATH)/index.txt"
$PAPELERA_ROOT_PATH = $HOME
$UNCOMPRESSED_TRASH_PATH = "$($PAPELERA_ROOT_PATH)/Papelera"
$COMPRESSED_TRASH_PATH = "$($PAPELERA_ROOT_PATH)/Papelera.zip"
$CUSTOM_SEPARATOR = "_IDX_TEMP_SEP_"